[package]
name = "grpc-client"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
solana-sdk = "3"
solana-transaction-status = "3"
tokio = "1.48.0"
yellowstone-grpc-client = "10.1.1"
yellowstone-grpc-proto = "10.1.1"
