[package]
name = "grpc-client"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
anyhow = "1.0.104"
bincode = "1.3.3"
solana-account-decoder-client-types = "4.2.2"
solana-sdk = { version = "4.0.0", default-features = false, features = ["full"] }
solana-transaction-context = "4.2.2"
solana-transaction-error = { version = "3.3.2", features = ["serde"] }
solana-transaction-status = { version = "4.2.2", features = ["agave-unstable-api"] }
tokio = "1.53.1"
yellowstone-grpc-client = "13.5.0"
yellowstone-grpc-proto = "12.7.0"

[workspace]
